"""initial schema

Revision ID: 9f2ba23b30c1
Revises: 
Create Date: 2026-07-01 09:45:59.897182

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f2ba23b30c1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encounter_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artifact_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('artifact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_encounter_id'), ['encounter_id'], unique=False)

    op.create_table('patients',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fhir_bundle_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_patient_ref'), ['patient_ref'], unique=True)

    op.create_table('encounters',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encounter_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_encounters_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_encounters_status'), ['status'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encounter_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approver_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approver_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artifact_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artifact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_encounter_id'), ['encounter_id'], unique=False)

    op.create_table('fhir_exports',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encounter_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fhir_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource', sa.JSON(), nullable=False),
    sa.Column('json_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fhir_exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fhir_exports_encounter_id'), ['encounter_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encounter_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('draft_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_source'), ['source'], unique=False)

    op.create_table('transcripts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encounter_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('utterances', sa.JSON(), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('asr_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('diarizer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcripts_encounter_id'), ['encounter_id'], unique=False)

    op.create_table('code_suggestions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encounter_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_suggestions_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_suggestions_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_suggestions_note_id'), ['note_id'], unique=False)

    op.create_table('referrals',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encounter_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('letter_text', sa.Text(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_note_id'), ['note_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_note_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_encounter_id'))

    op.drop_table('referrals')
    with op.batch_alter_table('code_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_suggestions_note_id'))
        batch_op.drop_index(batch_op.f('ix_code_suggestions_encounter_id'))
        batch_op.drop_index(batch_op.f('ix_code_suggestions_code'))

    op.drop_table('code_suggestions')
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcripts_encounter_id'))

    op.drop_table('transcripts')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_source'))
        batch_op.drop_index(batch_op.f('ix_notes_encounter_id'))

    op.drop_table('notes')
    with op.batch_alter_table('fhir_exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fhir_exports_encounter_id'))

    op.drop_table('fhir_exports')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_encounter_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encounters_status'))
        batch_op.drop_index(batch_op.f('ix_encounters_patient_id'))

    op.drop_table('encounters')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_patient_ref'))

    op.drop_table('patients')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_encounter_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
